# Chapter: 3. Getting started with Kargo
# Section: Creating the Argo CD Applications
# Kargo version: 1.12.1
# Status: UNVERIFIED

# tag::content[]
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-dev
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: demo:dev
  labels:
    kargo.akuity.io/project: demo
spec:
  project: default
  source:
    repoURL: https://github.com/kargobook/demo-gitops.git
    targetRevision: main
    path: charts/demo-app
    helm:
      releaseName: demo-app
      valueFiles:
      - ../../envs/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-pre-prod
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: demo:pre-prod
  labels:
    kargo.akuity.io/project: demo
spec:
  project: default
  source:
    repoURL: https://github.com/kargobook/demo-gitops.git
    targetRevision: main
    path: charts/demo-app
    helm:
      releaseName: demo-app
      valueFiles:
      - ../../envs/pre-prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-pre-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-prod
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: demo:prod
  labels:
    kargo.akuity.io/project: demo
spec:
  project: default
  source:
    repoURL: https://github.com/kargobook/demo-gitops.git
    targetRevision: main
    path: charts/demo-app
    helm:
      releaseName: demo-app
      valueFiles:
      - ../../envs/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

# end::content[]
