# Chapter: 3. Getting started with Kargo
# Section: The core resource model
# Kargo version: 1.11.0
# Status: UNVERIFIED
#
# This file is illustrative only. Freight is created by Kargo's Warehouse
# controller; you do not author Freight by hand. Shown here to make the
# resource's shape visible during the conceptual overview.

# tag::content[]
apiVersion: kargo.akuity.io/v1alpha1
kind: Freight
metadata:
  name: 666209fd9755a1e48bec6b27f5f447747410dd9e                                    # <1>
  namespace: demo
  annotations:
    kargo.akuity.io/alias: frozen-tauntaun                                          # <2>
origin:
  kind: Warehouse
  name: demo-app                                                                    # <3>
images:
- repoURL: ghcr.io/kargobook/demo-app
  tag: 1.2.0                                                                        # <4>
  digest: sha256:5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03   # <5>
# end::content[]
