# Chapter: 3. Getting started with Kargo
# Section: Defining the Stages
# Kargo version: 1.11.0
# Status: UNVERIFIED

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: pre-prod
  namespace: demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: demo-app
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/<your-github-username>/demo-gitops.git
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./repo
      - uses: kustomize-set-image
        config:
          path: ./repo/envs/pre-prod
          images:
          - image: ghcr.io/kargobook/demo-app
            digest: ${{ imageFrom("ghcr.io/kargobook/demo-app").Digest }}
      - uses: git-commit
        as: commit
        config:
          path: ./repo
          message: 'Promote to pre-prod: ${{ imageFrom("ghcr.io/kargobook/demo-app").Tag }}'
      - uses: git-push
        config:
          path: ./repo
          targetBranch: main
      - uses: argocd-update
        config:
          apps:
          - name: demo-pre-prod
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs['commit'].commit }}
