# Chapter: 4. Modeling your delivery: Warehouses, Freight, and Stage graphs
# Section: 4.4.4 Multi-service Stage graphs
# Kargo version: 1.x
# Status: VERIFIED

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargobook-demo
spec:
  requestedFreight:                                  # <1>
  - origin:
      kind: Warehouse
      name: payments-warehouse
    sources:
      stages:
      - payments-dev
  - origin:
      kind: Warehouse
      name: auth-warehouse                           # <2>
    sources:
      stages:
      - auth-dev
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/kargobook/demo-gitops.git
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./repo
      - uses: kustomize-set-image
        config:
          path: ./repo/apps/payments/envs/staging
          images:
          - image: ghcr.io/kargobook/payments-api
            tag: ${{ imageFrom("ghcr.io/kargobook/payments-api").Tag }}
      - uses: kustomize-set-image
        config:
          path: ./repo/apps/auth/envs/staging
          images:
          - image: ghcr.io/kargobook/auth-service
            tag: ${{ imageFrom("ghcr.io/kargobook/auth-service").Tag }}
      - uses: git-commit                             # <3>
        as: commit
        config:
          path: ./repo
          message: 'Promote payments-api and auth-service to staging'
      - uses: git-push
        config:
          path: ./repo
          targetBranch: main
      - uses: argocd-update
        config:
          apps:
          - name: payments-staging
            sources:
            - repoURL: ${{ vars.gitRepo }}
          - name: auth-staging
            sources:
            - repoURL: ${{ vars.gitRepo }}
