# Chapter: 4. Modeling your delivery: Warehouses, Freight, and Stage graphs
# Section: 4.3 Designing Stage graphs
# Kargo version: 1.12.1
# Status: UNVERIFIED

# tag::content[]
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: smoke
  namespace: demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: demo-app
    sources:
      stages:
      - dev                                    # <1>
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/kargobook/demo-gitops.git
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./repo
      - uses: yaml-update
        config:
          path: ./repo/envs/smoke/values.yaml  # <2>
          updates:
          - key: image.digest
            value: ${{ imageFrom("ghcr.io/kargobook/demo-app").Digest }}
      - uses: git-commit
        config:
          path: ./repo
          message: 'Promote to smoke: ${{ imageFrom("ghcr.io/kargobook/demo-app").Tag }}'
      - uses: git-push
        as: push
        config:
          path: ./repo
          targetBranch: main
      - uses: argocd-update
        config:
          apps:
          - name: demo-smoke
            sources:
            - repoURL: ${{ vars.gitRepo }}
              desiredRevision: ${{ outputs.push.commit }}
              updateTargetRevision: true
# end::content[]
