# Chapter: 4. Modeling your delivery: Warehouses, Freight, and Stage graphs
# Section: 4.2.2 Multi-artifact Freight
# Kargo version: 1.x
# Status: VERIFIED

apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: demo-app-multi
  namespace: kargobook-demo
spec:
  subscriptions:                                     # <1>
  - image:
      repoURL: ghcr.io/kargobook/demo-app
      semverConstraint: ^1.0.0
  - chart:                                           # <2>
      repoURL: oci://ghcr.io/kargobook/charts/demo-app
      semverConstraint: ^1.0.0
